I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 473, in script
    jump .break_1
ScriptError: could not find label 'problem_b.break_1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 473, in script
    jump .break_1
  File "G:\Ren'Py\renpy-8.0.2-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "G:\Ren'Py\renpy-8.0.2-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'problem_b.break_1'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Lexium PREVIEW - 0.2a
Mon Oct  3 08:37:10 2022
